# version: '3.8'

# services:
#   mysqldb:
#     image: mysql
#     container_name: mysqldb
#     environment:
#       - MYSQL_ROOT_PASSWORD=gonza123
#       - MYSQL_DATABASE=gonzalodb
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysqldata:/var/lib/mysql 
#     command: --default-authentication-plugin=mysql_native_password
#   app:
#     build: .
#     container_name: app
#     depends_on:
#       - mysqldb
#     links:
#       - mysqldb
#     ports:
#       - 4000:4000

# volumes:
#   mysqldata:

version: '3.8'

services:
  mysqldb:
    image: mysql:5.7  # Cambia la versión si necesitas
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=gonza123
      - MYSQL_DATABASE=gonzalodb
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql 

  app:
    build: .
    container_name: app
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - 4000:4000

volumes:
  mysqldata:
